export const parks = [
  {
    id: 1,
    name: 'Centreville Playground',
    address: 'Centreville St',
    city: 'Ozone Park',
    state: 'NY',
    zip_code: 11417,
    description: 'very clean',
    image_url: 'https://et710.com/website/jm/ozoneparkimages/parks1.jpg',
    phone: '(212)639-9675',
  },
  {
    id: 2,
    name: 'Phone Mini',
    address: 'North Conduit Avenue',
    city: 'Ozone Park',
    state: 'NY',
    zip_code: 11417,
    description: 'very clean',
    image_url: 'https://et710.com/website/jm/ozoneparkimages/parks2.jpg',
    phone: '(212)639-9675',
  },
  {
    id: 3,
    name: 'Phone Standard',
    address: '82nd Street',
    city: 'Ozone Park',
    state: 'NY',
    zip_code: 11417,
    description: 'very clean',
    image_url: 'https://et710.com/website/jm/ozoneparkimages/parks3.jpg',
    phone: '(212)639-9675',
  },
];
